<a href="https://colab.research.google.com/github/adithyaraj333/DATA-SCIENCE/blob/main/DATA_SCIENCE_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#ONES()
import numpy  as np
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [ ]:
import numpy as np
array1=np.array([[[1,2,3,4],
                  [3,5,7,9],
                  [2,1,3,4]]])
print(array1.)


In [ ]:
array1=np.array([1,2,3,4,5,6,])
array2=array1.reshape(2,3)
print(array2)

[[1 2 3]
 [4 5 6]]


***pandas***(panal data system)



panal is a open source data library used for data cleaning, data analysis,data manupulation and data visualisation,preperation,working with tabular format data or exel sheet



pandas data ***structure*** ***bold text***
pandas has mainly two types
1-series
2-data frames
#import pandas as pd

## ***series***
 series is a one dimensional labelled array

In [ ]:
import pandas as pd
marks=pd.Series([1,2,3,4,5,6,7])
print(marks)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64


In [ ]:
import pandas as pd
marks=pd.Series([1,221,3,4],index=["maths","physics","zoology","botony"])
print(marks)


maths        1
physics    221
zoology      3
botony       4
dtype: int64


In [ ]:
import pandas as pd
a=pd.Series(["anandhu","mahin","adhi","yaseen"],index=["BCA dept","BBA  dept","BCOM dept","BVOC dept"])
print(a)

BCA dept     anandhu
BBA  dept      mahin
BCOM dept       adhi
BVOC dept     yaseen
dtype: object


In [ ]:
import pandas as pd
a=pd.Series(["BCA dept","BBA  dept","BCOM dept","BVOC dept"],index=["anandhu","mahin","adhi","yaseen"])
print(a)

anandhu     BCA dept
mahin      BBA  dept
adhi       BCOM dept
yaseen     BVOC dept
dtype: object


In [ ]:
import pandas as pd
a=pd.Series(["BCA dept","BBA  dept","BCOM dept","BVOC dept"],index=["anandhu","mahin","adhi","yaseen"])
print(a["mahin"] )

BBA  dept


1.what is numpy and pandas

2.why do we use numpy and paandas

3.what is series

4.what is the diff between ;ist and numpy arrays

5.what is indexing and slicing

6.create a numpy array contains numbers from 1 to 20

7.create a panda series with doctors and department


## ANSWERS **bold text**
# **1**
. NUMPY--it is a python library
.PANDAS--pandas is a open source python library

# 2.**uses**   
numpy--used for working with arrary
pandas--used for data cleaning, data visualisation ,data manupulation,data analysis

# **3.SERIES**
series is a one dimensional labbeled array

# **4.**
list--

## ***DATA FRAME***